const enum FBKeys {
  app = "app",
  admin = "admin",
  advisors = "advisors",
  advisor_register = "advisor_register",
  advice_market = "advice_market",
  asset_data = "asset_data",
  contest_analytics = "contest_analytics",
  market_questions = "market_questions",
  "all.symbols" = "all.symbols",
  comments = "comments",
  competition = "competition",
  contest = "contest",
  deactivated = "deactivated",
  "error-logs" = "error-logs",
  etfs = "etfs",
  followers = "followers",
  following = "following",
  fidelity_issues = "fidelity_issues",
  advice_market_promo = "advice_market_promo",
  "linked-accounts" = "linked-accounts",
  linkedin = "linkedin",
  logos = "logos",
  logs = "logs",
  market = "market",
  market_reviews = "market_reviews",
  "market-state" = "market-state",
  messages = "messages",
  "mutual-funds" = "mutual-funds",
  networth = "networth",
  newsfeed = "newsfeed",
  "not-verified" = "not-verified",
  notifications = "notifications",
  "null-values" = "null-values",
  market_consultation = "market_consultation",
  "plaid-requests" = "plaid-requests",
  "player-id" = "player-id",
  "post-likes" = "post-likes",
  purchase = "purchase",
  portfolio = "portfolio",
  requests = "requests",

  "sector-weights" = "sector-weights",
  simulator = "simulator",
  "simulator-results" = "simulator-results",
  "simulator-net" = "simulator-net",
  "simulator-logs" = "simulator-logs",
  stripe_accnt = "stripe_accnt",
  "top-holdings" = "top-holdings",
  users = "users",
  verified = "verified",
  watchlist = "watchlist",
  post_views = "post_views",
  scheduled_notifications = "scheduled_notifications",
  market_financialPlans = "market_financialPlans",

  // NEWSFEED
  newsfeed_yhnews = "newsfeed_yhnews",
  newsfeed_congressTrades = "newsfeed_congressTrades",

  // PROFIT PICKS
  profit_picks_choices = "profit_picks_choices",
  profit_picks = "profit_picks",
  profit_picks_has_won = "profit_picks_has_won",
}

const enum FBSubKeys {
  accounts = "accounts",
  newsfeed_comments = "newsfeed-comments",
  user_networth = "user-networth",
  "user-notifications" = "user-notifications",
  cost_basis = "cost_basis",
  "cost-basis" = "cost-basis",
  contest_results = "contest_results",
  contest = "contest",
  simulator = "simulator",
  million = "million",
  DJI = "DJI",
  linked_accounts = "linked_accounts",
  error_catch = "error-catch",
  request = "request",
  schedules = "schedules",
  user_error = "user-error",
  user_following = "user-following",
  user_followers = "user-followers",
  portfolio_error = "portfolio_error",
  "user-watchlist" = "user-watchlist",
  "top-ten" = "top-ten",
  analytics_error = "analytics-error",
  watchlist_error = "watchlist-error",
  worker_error = "worker-error",
  top_movers_error = "top-movers-error",
  networth_error = "networth-error",
  portf_chart_error = "portfolio-chart-error",
  delete_token_error = "delete_token_error",
  stripe_purchase = "stripe_purchase",
  unread = "unread",
  requests = "requests",
  version = "version",

  // PROFIT PICKS
  profit_pick_winners = "profit_pick_winners",
  profit_pick_losers = "profit_pick_losers",
  profit_picks_has_won = "profit_picks_has_won",
}

const enum ERRKeys {
  comb_net_error = "comb_net_error",
  notifification_error = "notifification_error",
  sim_start_error = "sim_start_error",
  close_price_error = "close_price_error",
  plaid_error = "plaid_error",
  websocket_error = "websocket_error",
  update_app_error = "update_app_error",
  newsfeed_error = "newsfeed_error",
  advisor_error = "advisor_error",
  register_error = "register_error",
  advice_market_err = "advice_market_err",
  stripe_err = "stripe_err",
  social_error = "social_error",
  webhook_err = "webhook_err",
}

export { FBKeys, FBSubKeys, ERRKeys }
